-- 0001_init (down)
DROP TABLE IF EXISTS outbox CASCADE;
DROP FUNCTION IF EXISTS outbox_notify() CASCADE;
DROP TABLE IF EXISTS project_members CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;
DROP TYPE IF EXISTS task_status;
DROP TYPE IF EXISTS task_kind;
